print("Welcome to the tip calculator")
total_bill = float(input("What was the total bill? $"))
percent_tip = int(input("What percentage tip would you like to give? 10, 12 or 15? "))
people = int(input("How many people to split the bill? "))
tip_bill = total_bill+total_bill*(percent_tip/100)
spilt_bill = round(tip_bill/people,2)
print(f"Each person should pay: {spilt_bill}")